- type: antag
  id: Obsessed
  name: roles-antag-obsessed-name
  antagonist: true
  setPreference: true
  objective: roles-antag-obsessed-objective
  guides: [ Conspirators ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

- type: startingGear
  id: ObsessedGear
  storage:
    back:
    - TravelCamera

- type: antagSpecifier
  parent: RestrictedAntag
  id: Obsessed
  prefRoles:
  - Obsessed
  multiAntagSetting: NotExclusive
  blacklist:
    components:
    - AntagImmune
  startingGear: ObsessedGear
  mindRoles:
  - MindRoleObsessed
  briefing:
    text: obsessed-role-greeting
    color: "#DEA0CA"
    sound: /Audio/_Harmony/Misc/obsessed_greeting.ogg
